### ISSUE TITLE
Does GeoEasy accept entering coodenates other than Easting/Northing 

### ISSUE THREAD

**Issue by aefavant** [zsiki/GeoEasy#144]
Such as geo latlon or even straight from field Azimuth-Distance ? If so how?
Sorry if this is not the right place, but I am new to github and find this very overwhelming.
I wanted to use geoeasy also for manual values and study.

thanks
tony

**Comment by zsiki** [comment]
No, only projected coordinates are used/supported. You should re-project you ellipsoidal/spherical coordinates to a projected coordinate reference system (CRS).  You can use proj or gdal/ogr utilities to change (CRS).
All tho horizontal calculations are make on the a plane.
The only exception is the KML and GPX export where coordinates are changed to longitude, latitude on WGS84 ellipsoid,

I opened the discussions on my GitHub project. Next time if you have question you can open a discussion instead of an issue.
