### ISSUE TITLE
Nikon 332?

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#154]
Subj. See attach.

[26-04-2021_19-27-57.zip](https://github.com/zsiki/GeoEasy/files/6390610/26-04-2021_19-27-57.zip)

[INTEKO.zip](https://github.com/zsiki/GeoEasy/files/6390596/INTEKO.zip)

See also:
* https://geodesist.ru/threads/pomogite-perevesti-raw-dannye-v-dxf-ili-dvg.87558/#post-1007170
* https://geodesist.ru/threads/kak-konvertirovat-format-dc.78226/#post-890356

Subject: https://github.com/zsiki/GeoEasy/issues/64

**Comment by zsiki** [comment]
From the docs on http://www.geoglobex.it/wp-content/uploads/2015/07/NIKON-DTM-322-manuale.pdf there is an output format like SDR (.DC) but there are small differences :(. For example D9 instead of 09. Is there a documentation for nikon 332 dialect of sdr33 format?

The nikon raw format is simple, it should be implemented.

**Comment by zvezdochiot** [comment]
Hi @zsiki .

Hmm. Everything that I had, I laid out.

Maybe "help wanted"?

**Comment by zsiki** [comment]
I've found the documentation for nikon npl 332, but the pages for sdr33 output are the same as for 322. Unfortunately he files you send are different.
https://surveyinstrumentsales.com/PDFs/Manuals/Nikon-NPL-322+-Manual.pdf

**Comment by zvezdochiot** [comment]
Hi @zsiki .

I will not lie. The files are not mine. Have been posted on the forum (link). So you should trust the official documentation.

**Comment by zsiki** [comment]
I've added Nikon RAW format to input formats. Actually Metres, DDDMMSS, Zenith and NEZ coordinate order is supported. Otjerwise the file is not loaded.
