### ISSUE TITLE
Non-Ascii filename?

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#160]
ℹ️ OS: Win 10.

Filename: T1T2.sdr 🆗 

Filename: Станция T1,T2 (Алексей).sdr
```tcl
can't read "coo_rec": no such variable
can't read "coo_rec": no such variable
    while executing
"GetVal {38 138} $coo_rec"
    (procedure "AddCoo" line 9)
    invoked from within
"AddCoo $fa $pn $x $y $z $code"
    (procedure "SdrCoo" line 20)
    invoked from within
"SdrCoo $fa $buf $pn $code $start $len "
    ("08" arm line 13)
    invoked from within
"switch -exact [string range $buf 0 1] {
			"00" {	;# head record
				if {[string range $buf 4 8] == "SDR33"} {
					set pnLength 16
				}
				set un [..."
    (procedure "Sdr" line 43)
    invoked from within
"Sdr $fn"
    ("*.sdr" arm line 2)
    invoked from within
"switch -glob [string tolower $fn] {
				*.job {
					set res [Geodimeter $fn]
					if {$res == 0} {	;# try to load are too
						set fn1 [file rootnam..."
    (procedure "MenuLoad" line 32)
    invoked from within
"MenuLoad ."
    (menu invoke)
```

**Comment by zsiki** [comment]
The file name of the loaded data set is used internally as a variable name. So it is a serious restriction to allowable file names. Until this issue is not solved you have to use letters of the English ABC, the underscore and numbers in the file name.
Besides _geoLoaded_ and _geoLoadedDir_ lists a third is necessary for the internally used array 

- name _geoLoadedDir_ full path to the selected file name (e.g.  _/home/user/GeoEasy/demodata/Станция T1,T2 (Алексей).geo_, it is used to save
- _geoLoaded_ name part of the loaded dataset without extension (e.g. _Станция T1,T2 (Алексей)_), it is displayed in the GUI
- _geoArray_ internally used name for the arrays to store parts of datasets (e.g. _dataset1_, three arrays are used _dataset1_geo_, _dataset1_coo_, _dataset1_par_)

**Comment by zsiki** [comment]
Instead of a new array the geoLoaded list is changed to store internal names (fb_n - where n is an ordinal number). New function added to handle internal a short and full names.
